### ISSUE TITLE
problem with torch._six on latest pytorch

### ISSUE THREAD

**Issue by liuyanyi** [ucbrise/actnn#15]
Hi, thanks for your great work, but there's some wrong with latest torch.
When I'm trying to import actnn on pytorch1.9, I faced an error

> \>\>\>import actnn
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/workspace/actnn-main/actnn/actnn/\_\_init\_\_.py", line 1, in <module>
>     from . import dataloader
>   File "/workspace/actnn-main/actnn/actnn/dataloader.py", line 16, in <module>
>     from torch._six import queue, string_classes
> ImportError: cannot import name 'queue' from 'torch._six' (/miniconda3/lib/python3.8/site-packages/torch/_six.py)

then I compare the difference with torch1.9 and torch1.7
there is a [commit ](https://github.com/pytorch/pytorch/commit/58eb23378f2a376565a66ac32c93a316c45b6131)in torch and they remove some import in torch._six, then I revert torch._six to old version so that actnn can work well.

Maybe just directly `import queue` it could work well.
other import from torch._six should fix too.

**Comment by merrymercy** [comment]
Thanks for reporting this. If you find a solution, could you send a pull request to fix this?
