### ISSUE TITLE
A kind suggestion on the pytorch version.

### ISSUE THREAD

**Issue by HeGsnS** [ucbrise/actnn#25]
This is a kind suggestion to the authors to revise the required pytorch version to "torch >= 1.7.1" and "torch <= 1.8.0" in the readme file.

**Comment by merrymercy** [comment]
Thanks for the suggestion.
It is updated https://github.com/ucbrise/actnn/commit/370bc9fe5cd8a64d817d5cc3924c6d3a2051db92
