### ISSUE TITLE
how to avoid memory fragmentation in ActNN?

### ISSUE THREAD

**Issue by Jack47** [ucbrise/actnn#36]
May I known how you guys implemented this defragmentation in ActNN?
![wecom-temp-63c4a7a412756448a2179e2b801edcd5](https://user-images.githubusercontent.com/1720972/178087525-8ce035f6-48e8-4d40-846e-ab69d4e4891e.png)

In my model training experience: smaller MAX_SPLIT_SIZE, worse performance. bigger MAX_SPLIT_SIZE, will finally result  OOM

**Comment by merrymercy** [comment]
The corresponding code is here https://github.com/ucbrise/actnn/blob/370bc9fe5cd8a64d817d5cc3924c6d3a2051db92/actnn/actnn/conf.py#L26-L31

**Comment by Jack47** [comment]
Great thanks, got that. use malloc instead of caching allocator for large size
